### ISSUE TITLE
No requiments.txt

### ISSUE THREAD

**Issue by Welsonpeaches** [PPicku/H.D.D-System#1]

**Comment by GID0317** [comment]
you can use this for now

pip install PyQt5
pip install pywinstyles
pip install requests
pip install pygame
pip install systemInfo
pip install "PyQt-Fluent-Widgets[full]" -i https://pypi.org/simple/
pip install cachelib
pip install wmi

**Comment by Welsonpeaches** [comment]
行，知道了，谢谢
您可以改一下readme么
